#pragma once

#include "ApplicationManager.h"

#include "Actions\AddRectAction.h"
#include "Actions\AddLineAction.h"
#include "Actions\AddEllipseAction.h"
#include "Actions\AddTriangleAction.h"
#include "Actions\AddRhombusAction.h"
#include "Actions\SelectFigureAction.h"
#include "Actions\ChangeDrawColorAction.h"
#include "Actions\ChangeFillColorAction.h"
#include "Actions\DeleteFigureAction.h"
#include "Actions\SendToFront.h"
#include "Actions\SendToBack.h"
#include "Actions\loadAction.h"
#include "Actions\SaveAction.h"
#include "Actions\Exit.h"
#include "Actions\saveByTypeAction.h"
//////////////////////////////////////////////////////////////////////////////////////////////////////  MohamedAdel
#include "Actions\ToPlayAction.h"
#include "Actions\PickByType.h"
#include "Actions\PickByColor.h"
#include "Actions\ToDrawAction.h"
#include "Actions\Sound.h"
//////////////////////////////////////////////////////////////////////////////////////////////////////
#include "Figures\CFigure.h"
#include "Figures\CEllipse.h"
#include "Figures\CFigure.h"
#include "Figures\CLine.h"
#include "Figures\CRectangle.h"
#include "Figures\CRhombus.h"
#include "Figures\CTriangle.h"
#include "Actions\CopyAction.h"
#include "Actions\CutAction.h"
#include "Actions\PasteAction.h"
